### ISSUE TITLE
Draw robot perimeter

### ISSUE THREAD

**Issue by DrewTheRat** [Endoman123/motion-profile-generator#16]
Add a robot length and width to the configuration. Draw a rectangle of those dimensions centered on each waypoint and angled based on the waypoint's angle, to show the robot position at that waypoint. 

## TODO:
- [ ] New section "Robot Dimensions"
- [x] New source traj level "Waypoints, Source, and Robot Bounds"

**Comment by Endoman123** [comment]
## TODO:
- [ ] Add new section for robot dimensions
- [ ] Add new source traj level for robot rect display
